import { createContext, useContext, useMemo, useState } from 'react';
import { BrowserRouter, Link, Route, Routes, useNavigate, useParams } from 'react-router-dom';
import Home from './Home';
import LoginPage from './LoginPage';
import { request, TOKEN_KEY } from './api';

const CartContext = createContext(null);
const CART_KEY = 'routebite_cart';
const formatMoney = (value) => `${Number(value || 0).toLocaleString('vi-VN')}đ`;
const demoMenu = { id: 'mock-com-tam', name: 'Cơm Tấm Mẫu', address: 'Quận 1, TP. Hồ Chí Minh', rating: 4.8, menuItems: [{ id: 'demo-com-tam', name: 'Cơm tấm sườn bì chả', description: 'Sườn nướng, bì, chả trứng và đồ chua', price: 60000, available: true }, { id: 'demo-tra-dao', name: 'Trà đào cam sả', description: 'Ly mát lạnh', price: 25000, available: true }] };

function Header() {
  const navigate = useNavigate();
  const { cart } = useContext(CartContext);
  const user = JSON.parse(localStorage.getItem('routebite_user') || 'null');
  return <header className="consumer-header"><Link className="consumer-logo" to="/">RouteBite</Link><nav><Link className="consumer-nav active" to="/">Trang chủ</Link><Link className="consumer-nav" to="/kham-pha">Khám phá</Link><Link className="consumer-nav" to="/my-orders">Đơn của tôi</Link><Link className="consumer-nav" to="/my-carts">Giỏ của tôi{cart.length ? ` (${cart.reduce((s, item) => s + item.quantity, 0)})` : ''}</Link></nav><div className="account-menu"><button className="bell-icon" type="button" aria-label="Thông báo"><span /></button><button className="profile-trigger" type="button" onClick={() => navigate(user ? (user.role === 'customer' ? '/my-orders' : '/merchant') : '/login')}>{user?.fullName?.slice(0, 2).toUpperCase() || 'DC'}</button></div></header>;
}

function RestaurantMenu() {
  const { id } = useParams(); const navigate = useNavigate(); const { add } = useContext(CartContext);
  const isDemo = id.startsWith('mock-'); const [restaurant, setRestaurant] = useState(isDemo ? demoMenu : null); const [error, setError] = useState(''); const [pickup, setPickup] = useState('15');
  useState(() => { if (!isDemo) request(`/restaurants/${id}`, { authorized: false }).then(setRestaurant).catch((e) => setError(e.message)); });
  if (error) return <Page title="Không mở được menu">{error}</Page>;
  if (!restaurant) return <Page title="Đang tải menu…" />;
  return <main className="app-page"><button className="back-link" onClick={() => navigate(-1)}>← Quay lại</button><section className="restaurant-hero"><div><p>GHÉ LẤY MANG ĐI</p><h1>{restaurant.name}</h1><span>{restaurant.address} · ⭐ {restaurant.rating || 'Mới'}</span></div><a className="btn secondary" target="_blank" rel="noreferrer" href={`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(restaurant.address)}`}>Chỉ đường</a></section><section className="booking-card"><strong>Thời gian ghé lấy</strong><select value={pickup} onChange={(e) => setPickup(e.target.value)}><option value="15">Sau 15 phút</option><option value="30">Sau 30 phút</option><option value="45">Sau 45 phút</option></select></section><section className="food-category"><h2>🔥 Món bán chạy nhất</h2>{(restaurant.menuItems || []).filter((item) => item.available).map((item) => <article className="food-menu-row" key={item.id}><div><h3>{item.name}</h3><p>{item.description || 'Món ngon của quán'}</p><strong>{formatMoney(item.price)}</strong></div><button className="add-food" onClick={() => add({ ...item, restaurantId: restaurant.id, restaurantName: restaurant.name, pickupMinutes: Number(pickup) })}>+</button></article>)}</section><Link className="floating-cart" to="/my-carts">Xem giỏ hàng</Link></main>;
}

function CartPage() {
  const navigate = useNavigate(); const { cart, change, clear } = useContext(CartContext); const routeEta = Math.max(1, Number(localStorage.getItem('routebite_route_eta_minutes')) || 15); const [method, setMethod] = useState('cash'); const [pickupType, setPickupType] = useState('asap'); const [minutes, setMinutes] = useState(routeEta); const [scheduledTime, setScheduledTime] = useState(''); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  const total = cart.reduce((sum, item) => sum + Number(item.price) * item.quantity, 0);
  async function checkout() { if (!cart.length) return; if (!localStorage.getItem(TOKEN_KEY)) return navigate('/login'); setBusy(true); setMessage(''); try { const first = cart[0]; const pickupOption = pickupType === 'asap' ? { type: 'asap', estimatedPickupMinutes: Number(minutes) } : { type: 'scheduled', scheduledTime: new Date(scheduledTime).toISOString() }; const order = await request('/orders', { method: 'POST', body: { restaurantId: first.restaurantId, pickupOption, payment: { method }, items: cart.map((item) => ({ menuItemId: item.id, quantity: item.quantity })) } }); if (method === 'vnpay') { const payment = await request('/payments/create', { method: 'POST', body: { orderId: order.id } }); if (!payment.checkoutUrl) throw new Error('Không tạo được liên kết thanh toán VNPAY'); clear(); window.location.assign(payment.checkoutUrl); return; } setMessage(`Đơn ${order.orderCode} đã đặt. Thanh toán tiền mặt khi ghé lấy.`); clear(); } catch (e) { setMessage(e.message); } finally { setBusy(false); } }
  return <main className="app-page cart-page-v2"><div className="page-intro"><p>GIỎ HÀNG</p><h1>Ghé lấy mang đi</h1></div>{cart.length ? <div className="cart-layout-v2"><section className="cart-lines">{cart.map((item) => <article className="cart-line" key={item.id}><div><h3>{item.name}</h3><strong>{formatMoney(item.price)}</strong></div><div className="qty-control"><button onClick={() => change(item.id, -1)}>−</button><span>{item.quantity}</span><button onClick={() => change(item.id, 1)}>+</button></div></article>)}</section><aside className="cart-summary-v2"><strong>Tổng cộng: {formatMoney(total)}</strong><fieldset className="payment-methods"><legend>Giờ lấy hàng</legend><label><input type="radio" checked={pickupType === 'asap'} onChange={() => setPickupType('asap')} /> Lấy sớm nhất</label>{pickupType === 'asap' && <select value={minutes} onChange={(e) => setMinutes(e.target.value)}><option value={routeEta}>Theo lộ trình: khoảng {routeEta} phút</option><option value="15">Sau khoảng 15 phút</option><option value="30">Sau khoảng 30 phút</option><option value="45">Sau khoảng 45 phút</option></select>}<label><input type="radio" checked={pickupType === 'scheduled'} onChange={() => setPickupType('scheduled')} /> Hẹn giờ lấy món</label>{pickupType === 'scheduled' && <input type="datetime-local" value={scheduledTime} onChange={(e) => setScheduledTime(e.target.value)} required />}</fieldset><fieldset className="payment-methods"><legend>Phương thức thanh toán</legend><label><input type="radio" checked={method === 'cash'} onChange={() => setMethod('cash')} /> Tiền mặt khi ghé lấy</label><label><input type="radio" checked={method === 'vnpay'} onChange={() => setMethod('vnpay')} /> Cổng VNPAY (QR / Thẻ ATM / Visa)</label></fieldset><button disabled={busy || (pickupType === 'scheduled' && !scheduledTime)} onClick={checkout}>{busy ? 'Đang tạo đơn…' : method === 'vnpay' ? 'Tiếp tục đến VNPAY' : 'Đặt hàng'}</button>{message && <p>{message}</p>}</aside></div> : <section className="orders-empty-v2">Giỏ hàng đang trống. Hãy chọn món từ menu quán.</section>}</main>;
}

function OrdersPage() { const [orders, setOrders] = useState(null); const [error, setError] = useState(''); useState(() => { if (!localStorage.getItem(TOKEN_KEY)) { setOrders([]); return; } request('/orders').then(setOrders).catch((e) => setError(e.message)); }); if (!localStorage.getItem(TOKEN_KEY)) return <Page title="Đơn của tôi">Vui lòng <Link to="/login">đăng nhập</Link> để xem đơn hàng.</Page>; if (!orders) return <Page title="Đơn của tôi">Đang tải…</Page>; return <main className="app-page orders-page-v2"><div className="page-intro"><p>ĐƠN HÀNG</p><h1>Đơn của tôi</h1></div>{error ? <p>{error}</p> : orders.length ? <section className="orders-list-v2">{orders.map((order) => <article className="order-card-v2" key={order.id}><div className="order-card-top"><div><small>{new Date(order.createdAt).toLocaleString('vi-VN')}</small><h3>{order.restaurant?.name}</h3><p>{order.orderCode}</p></div><span className={`order-status-v2 status-${order.status}`}>{order.status}</span></div><div className="order-card-foot"><strong>{formatMoney(order.totalAmount)}</strong><span>{order.pickupType === 'scheduled' ? `Hẹn lấy lúc ${new Date(order.estimatedPickupAt).toLocaleTimeString('vi-VN', { hour: '2-digit', minute: '2-digit' })}` : `Lấy sau khoảng ${Math.max(0, Math.ceil((new Date(order.estimatedPickupAt).getTime() - Date.now()) / 60000))} phút`}</span></div></article>)}</section> : <section className="orders-empty-v2">Bạn chưa có đơn hàng nào.</section>}</main>; }
function Page({ title, children }) { return <main className="app-page"><div className="page-intro"><p>ROUTEBITE</p><h1>{title}</h1></div><section className="orders-empty-v2">{children || 'Tính năng đang được đồng bộ.'}</section></main>; }
function MerchantPage() { const user = JSON.parse(localStorage.getItem('routebite_user') || 'null'); return <Page title="Khu vực quản lý">{user?.role === 'merchant' || user?.role === 'admin' ? 'Bạn đã đăng nhập với quyền quản lý quán. API tạo/sửa quán đã được backend bảo vệ theo role.' : 'Trang này chỉ dành cho merchant hoặc admin.'}</Page>; }
function AppShell() { const [cart, setCart] = useState(() => JSON.parse(localStorage.getItem(CART_KEY) || '[]')); const value = useMemo(() => ({ cart, add(item) { setCart((old) => { const same = old.find((entry) => entry.id === item.id); const next = same ? old.map((entry) => entry.id === item.id ? { ...entry, quantity: entry.quantity + 1 } : entry) : [...old.filter((entry) => entry.restaurantId === item.restaurantId), { ...item, quantity: 1 }]; localStorage.setItem(CART_KEY, JSON.stringify(next)); return next; }); }, change(id, step) { setCart((old) => { const next = old.map((entry) => entry.id === id ? { ...entry, quantity: entry.quantity + step } : entry).filter((entry) => entry.quantity > 0); localStorage.setItem(CART_KEY, JSON.stringify(next)); return next; }); }, clear() { localStorage.removeItem(CART_KEY); setCart([]); } }), [cart]); return <CartContext.Provider value={value}><Header /><Routes><Route path="/" element={<Home />} /><Route path="/login" element={<LoginPage />} /><Route path="/restaurant/:id" element={<RestaurantMenu />} /><Route path="/my-carts" element={<CartPage />} /><Route path="/my-orders" element={<OrdersPage />} /><Route path="/merchant" element={<MerchantPage />} /><Route path="/kham-pha" element={<Page title="Khám phá quán" />} /></Routes></CartContext.Provider>; }
export default function App() { return <BrowserRouter><AppShell /></BrowserRouter>; }
