import React, { useEffect, useState } from 'react';
import ReactDOM from 'react-dom/client';

const h = React.createElement;
const API = (window.ROUTEBITE_CONFIG || {}).apiBase || 'http://127.0.0.1:3000/api';
const TOKEN = 'routebite_access_token';
async function request(path, opts = {}) { const token = localStorage.getItem(TOKEN); const r = await fetch(`${API}${path}`, { method: opts.method || 'GET', headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) }, body: opts.body ? JSON.stringify(opts.body) : undefined }); const d = await r.json().catch(() => ({})); if (!r.ok) throw new Error(d.message || 'KhÃ´ng thá»ƒ káº¿t ná»‘i mÃ¡y chá»§'); return d; }
const navItems = [['home','Trang chá»§'],['browse','KhÃ¡m phÃ¡'],['orders','ÄÆ¡n cá»§a tÃ´i']];
function Header({page,setPage,user,login,logout}) { return h('header',{className:'consumer-header'},[h('button',{className:'consumer-logo',onClick:()=>setPage('home')},'RouteBite'),h('nav',null,navItems.map(([id,label])=>h('button',{key:id,className:`consumer-nav ${page===id?'active':''}`,onClick:()=>setPage(id)},label))),h('div',{className:'account-menu'},user?h('button',{className:'profile-trigger',onClick:logout},'ÄÄƒng xuáº¥t'):h('button',{className:'profile-trigger',onClick:login},'ÄÄƒng nháº­p'))]); }
C:\Users\DELL
function Orders() { const [orders,setOrders]=useState([]),[filter,setFilter]=useState('all'),[error,setError]=useState('');useEffect(()=>{request('/orders/my?limit=30').then(d=>setOrders(d.data||d)).catch(e=>setError(e.message))},[]);const group={processing:['pending_payment','pending','paid','confirmed','preparing','ready'],completed:['completed'],cancelled:['cancelled']};const filtered=filter==='all'?orders:orders.filter(o=>group[filter].includes(o.status));const label={pending:'Chá» xÃ¡c nháº­n',confirmed:'ÄÃ£ xÃ¡c nháº­n',preparing:'Äang chuáº©n bá»‹',ready:'Sáºµn sÃ ng láº¥y',completed:'HoÃ n thÃ nh',cancelled:'ÄÃ£ há»§y'};return h('main',{className:'app-page orders-page-v2'},[h('div',{className:'page-intro'},[h('p',null,'ÄÆ N HÃ€NG'),h('h1',null,'ÄÆ¡n cá»§a tÃ´i'),h('span',null,'Theo dÃµi tráº¡ng thÃ¡i vÃ  tiáº¿n Ä‘á»™ Ä‘Æ¡n hÃ ng cá»§a báº¡n.')]),h('div',{className:'order-filter-row'},[['all','Táº¥t cáº£'],['processing','Äang xá»­ lÃ½'],['completed','HoÃ n thÃ nh'],['cancelled','ÄÃ£ há»§y']].map(([k,v])=>h('button',{key:k,className:`order-filter-chip ${filter===k?'active':''}`,onClick:()=>setFilter(k)},[v,h('strong',null,k==='all'?orders.length:orders.filter(o=>group[k].includes(o.status)).length)]))),error?h('section',{className:'orders-empty-v2'},error):filtered.length?h('section',{className:'orders-list-v2'},filtered.map(o=>h('article',{className:'order-card-v2',key:o.id},[h('div',{className:'order-card-top'},[h('div',null,[h('small',null,new Date(o.createdAt).toLocaleDateString('vi-VN')),h('h3',null,o.restaurantName||o.restaurant?.name||'NhÃ  hÃ ng'),h('p',null,o.code||o.id)]),h('span',{className:`order-status-v2 status-${o.status}`},label[o.status]||o.status)]),h('div',{className:'order-card-foot'},[h('strong',null,`${Number(o.totalAmount||0).toLocaleString('vi-VN')}Ä‘`),h('span',null,`${o.items?.length||0} mÃ³n`)]))])):h('section',{className:'orders-empty-v2'},[h('h2',null,'ChÆ°a cÃ³ Ä‘Æ¡n hÃ ng nÃ o'),h('p',null,'KhÃ¡m phÃ¡ cÃ¡c quÃ¡n Äƒn vÃ  Ä‘áº·t mÃ³n cho hÃ nh trÃ¬nh cá»§a báº¡n.')])]); }
function Browse() { return h('main',{className:'app-page browse-page-v2'},[h('div',{className:'page-intro'},[h('p',null,'KHÃM PHÃ Tá»° DO'),h('h1',null,'QuÃ¡n ngon Ä‘ang chá» báº¡n')]),h('section',{className:'route-empty-v2'},'Chá»n hÃ nh trÃ¬nh á»Ÿ trang chá»§ Ä‘á»ƒ xem cÃ¡c quÃ¡n phÃ¹ há»£p.')]); }
function Login({done}) { const [error,setError]=useState('');const submit=async e=>{e.preventDefault();try{const f=e.currentTarget,d=await request('/auth/login',{method:'POST',body:{email:f.email.value,password:f.password.value}});localStorage.setItem(TOKEN,d.accessToken);done(d.user)}catch(e){setError(e.message)}};return h('main',{className:'app-page'},h('section',{className:'panel',style:{maxWidth:460,margin:'55px auto',padding:28}},[h('h2',null,'ÄÄƒng nháº­p RouteBite'),h('form',{className:'grid-form',onSubmit:submit},[h('input',{name:'email',type:'email',placeholder:'Email',required:true}),h('input',{name:'password',type:'password',placeholder:'Máº­t kháº©u',required:true}),error?h('small',{style:{color:'#b3261e'}},error):null,h('button',{className:'btn primary'},'ÄÄƒng nháº­p')])]))); }
function App(){const [user,setUser]=useState(null),[page,setPage]=useState('home');useEffect(()=>{if(localStorage.getItem(TOKEN))request('/auth/me').then(setUser).catch(()=>localStorage.removeItem(TOKEN))},[]);if(page==='login')return h(Login,{done:u=>{setUser(u);setPage('home')}});return h('div',null,[h(Header,{page,setPage,user,login:()=>setPage('login'),logout:()=>{localStorage.removeItem(TOKEN);setUser(null)}}),page==='home'?h(Home,{setPage}):page==='orders'?h(Orders):h(Browse)]);} ReactDOM.createRoot(document.getElementById('root')).render(h(App));
