import 'package:flutter/material.dart';
import 'api_client.dart';

// iOS simulator uses localhost; physical iPhone must use the computer LAN IP.
const api = ApiClient(String.fromEnvironment('API_URL', defaultValue: 'http://localhost:3000'));
void main() => runApp(const RouteBiteApp());
class RouteBiteApp extends StatelessWidget { const RouteBiteApp({super.key}); @override Widget build(BuildContext context) => MaterialApp(title: 'RouteBite', theme: ThemeData(colorSchemeSeed: Colors.orange, useMaterial3: true), home: const LoginPage()); }
class LoginPage extends StatefulWidget { const LoginPage({super.key}); @override State<LoginPage> createState() => _LoginPageState(); }
class _LoginPageState extends State<LoginPage> { final email=TextEditingController(); final password=TextEditingController(); bool loading=false; Future<void> login() async { setState(()=>loading=true); try { final result=await api.post('/auth/login',{'email':email.text.trim(),'password':password.text},authorized:false); await api.saveSession(result); if(mounted) Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>const RouteSearchPage())); } catch(e) { if(mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('$e'))); } finally { if(mounted) setState(()=>loading=false); } } @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('RouteBite')),body:Padding(padding:const EdgeInsets.all(24),child:Column(children:[TextField(controller:email,keyboardType:TextInputType.emailAddress,decoration:const InputDecoration(labelText:'Email')),TextField(controller:password,obscureText:true,decoration:const InputDecoration(labelText:'Mật khẩu')),const SizedBox(height:24),FilledButton(onPressed:loading?null:login,child:Text(loading?'Đang đăng nhập...':'Đăng nhập'))])); }
class RouteSearchPage extends StatefulWidget { const RouteSearchPage({super.key}); @override State<RouteSearchPage> createState()=>_RouteSearchPageState(); }
class _RouteSearchPageState extends State<RouteSearchPage> { final aLat=TextEditingController(text:'10.7769'),aLng=TextEditingController(text:'106.7009'),bLat=TextEditingController(text:'10.7860'),bLng=TextEditingController(text:'106.6950'); List<dynamic> restaurants=[]; bool loading=false; Future<void> search() async { setState(()=>loading=true); try { final data=await api.post('/search/route',{'pointA':{'latitude':double.parse(aLat.text),'longitude':double.parse(aLng.text)},'pointB':{'latitude':double.parse(bLat.text),'longitude':double.parse(bLng.text)},'radius':500}); setState(()=>restaurants=data['restaurants'] as List<dynamic>); } catch(e) { if(mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('$e'))); } finally { if(mounted) setState(()=>loading=false); } } @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Tìm quán tiện đường')),body:Column(children:[Padding(padding:const EdgeInsets.all(12),child:Wrap(spacing:8,runSpacing:8,children:[SizedBox(width:150,child:TextField(controller:aLat,decoration:const InputDecoration(labelText:'A - vĩ độ'))),SizedBox(width:150,child:TextField(controller:aLng,decoration:const InputDecoration(labelText:'A - kinh độ'))),SizedBox(width:150,child:TextField(controller:bLat,decoration:const InputDecoration(labelText:'B - vĩ độ'))),SizedBox(width:150,child:TextField(controller:bLng,decoration:const InputDecoration(labelText:'B - kinh độ'))),FilledButton(onPressed:loading?null:search,child:const Text('Tìm quán'))])),Expanded(child:ListView.builder(itemCount:restaurants.length,itemBuilder:(_,i){final r=restaurants[i] as Map<String,dynamic>;return Card(child:ListTile(title:Text(r['name'] as String),subtitle:Text('${r['address']} • ${r['distance_meters']} m'),trailing:Text('★ ${r['rating']}'),onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>RestaurantPage(restaurant:r))));}))])); }
class RestaurantPage extends StatelessWidget { const RestaurantPage({super.key,required this.restaurant}); final Map<String,dynamic> restaurant; @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text(restaurant['name'] as String)),body:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(restaurant['address'] as String),const SizedBox(height:16),const Text('Chọn món trong menu và tạo đơn take-away tại màn hình này.'),const Spacer(),FilledButton(onPressed:(){},child:const Text('Đặt món'))])) ; }
